// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itlyiyknweernejmpibd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0bHlpeWtud2Vlcm5lam1waWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODcxOTgsImV4cCI6MjA2ODU2MzE5OH0.rFUcCvI8OZf_xNtdS71e21AIG4AvSGFPkcXcRnDwOUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});